[[main]]
  identifier = "home"
  name = "Home"
  weight = 1
  url = "/"
  [main.params]
    icon = '<i class="fas fa-home"></i>'
[[main]]
  identifier = "blog"
  name = "Blog"
  weight = 2
  [main.params]
    icon = '<i class="fas fa-fw fa-blog"></i>'

